import { BuildingConfig } from "@/types/building";

export const BUILDINGS: BuildingConfig[] = [
  {
    id: "modcodes-hq",
    name: "MODCODES HQ",
    subtitle: "Flagship Project",
    position: [0, 0, 0],
    scale: [2.8, 4.5, 2.8],
    color: "#e8d5c4",
    emissive: "#ffd700",
    roofColor: "#8b7355",
    windowPattern: "grid",
    content: {
      title: "MODCODES",
      subtitle: "Flagship Product",
      paragraphs: [
        "MODCODES is not a project. It is a product.",
        "An AI-powered student productivity platform designed to solve real academic problems: missed assignments, deadline chaos, disorganized planning.",
        "Built with Python, FastAPI, SQLite, Ollama local LLMs, speech recognition, and text-to-speech.",
        "Currently in Beta. Not a prototype. Not a concept. A working product that students actually use.",
      ],
      tags: ["Python", "FastAPI", "SQLite", "Ollama", "Speech Recognition"],
      links: [
        { label: "Website Coming Soon", url: "#", icon: "rocket" },
      ],
    },
  },
  {
    id: "project-factory",
    name: "Project Factory",
    subtitle: "Shipped Work",
    position: [-6, 0, -3],
    scale: [3.5, 2.5, 2.2],
    color: "#d4c5b0",
    emissive: "#4a90d9",
    roofColor: "#6b5b45",
    windowPattern: "stripe",
    content: {
      title: "Project Factory",
      subtitle: "Real Products, Real Clients",
      paragraphs: [
        "Every project in this factory has been shipped, deployed, or delivered.",
        "Vishwanath Insurance Portfolio — a production website delivered to a real client with Google Sheets integration, responsive design, and a consultation workflow.",
        "CodeShortsBot v2 — an autonomous content pipeline that researches topics, generates scripts, creates assets, assembles videos, and prepares YouTube Shorts. No human involvement.",
        "These are not demos. These are products that exist in the real world.",
      ],
      tags: ["Next.js", "Google Sheets", "FFmpeg", "Playwright", "Ollama"],
      links: [
        {
          label: "View Vishwanath Insurance",
          url: "https://vishwanath-malusare.vercel.app",
          icon: "external",
        },
      ],
    },
  },
  {
    id: "achievement-tower",
    name: "Achievement Tower",
    subtitle: "Evidence & Recognition",
    position: [6, 0, -2],
    scale: [1.8, 5.5, 1.8],
    color: "#f0e6d8",
    emissive: "#ffd700",
    roofColor: "#a08060",
    windowPattern: "dots",
    content: {
      title: "Achievement Tower",
      subtitle: "What I Have Earned",
      paragraphs: [
        "Best Performing Intern at Kaevron Technologies — not for attendance, but for building automation systems, delivering projects, and demonstrating ownership.",
        "SIH-2025 Special Recognition — led a first-year team with zero prior hackathon experience to win recognition against senior competitors.",
        "1 client website delivered and deployed. Not planned. Not mocked. Delivered.",
        "Everything here is evidence. Not claims.",
      ],
      tags: [
        "Kaevron Technologies",
        "Best Intern",
        "SIH-2025",
        "Client Delivery",
      ],
      links: [],
    },
  },
  {
    id: "innovation-lab",
    name: "Innovation Lab",
    subtitle: "Future Builds",
    position: [-4, 0, -8],
    scale: [3, 3, 3],
    color: "#c8d8e8",
    emissive: "#00ccff",
    roofColor: "#5a7a9a",
    windowPattern: "grid",
    content: {
      title: "Innovation Lab",
      subtitle: "What I Am Building Next",
      paragraphs: [
        "This is where ideas get stress-tested before they become products.",
        "Own AI IDE — not another code editor. A development environment built around how I actually think and build. Planned architecture: plugin-based, local-first, AI-native.",
        "Custom Programming Language — designed for teaching and rapid prototyping. The language itself is the project.",
        "Open Source tools that solve problems I have personally faced. Not theoretical. Not theoretical. Practical, battle-tested utilities.",
      ],
      tags: ["AI IDE", "Compiler Design", "Language Theory", "Open Source"],
      links: [
        { label: "Roadmap Coming Soon", url: "#", icon: "rocket" },
      ],
    },
  },
  {
    id: "developer-museum",
    name: "Developer Museum",
    subtitle: "Journey & Growth",
    position: [4, 0, -8],
    scale: [2.5, 4, 2.5],
    color: "#e8d8c8",
    emissive: "#ff6b35",
    roofColor: "#8a6a4a",
    windowPattern: "stripe",
    content: {
      title: "Developer Museum",
      subtitle: "The Timeline",
      paragraphs: [
        "Started with curiosity. Built with obsession. Shipped with purpose.",
        "From first line of code to deploying production systems — every step documented, every failure analyzed, every success earned.",
        "Diploma in Computer Science. Not a degree. A foundation. The real education happens here, in the district.",
        "Best Performing Intern. SIH-2025 Recognition. Client delivery. These are not just titles — they are proof of work.",
      ],
      tags: ["Journey", "Growth", "Milestones", "Proof of Work"],
      links: [],
    },
  },
  {
    id: "open-source-center",
    name: "Open Source Center",
    subtitle: "Community & Contribution",
    position: [0, 0, -11],
    scale: [3.5, 2.8, 2.5],
    color: "#d0d8e0",
    emissive: "#22c55e",
    roofColor: "#4a6a5a",
    windowPattern: "dots",
    content: {
      title: "Open Source Center",
      subtitle: "Building in Public",
      paragraphs: [
        "Every project here is built with transparency. Code is public. Decisions are documented. Failures are shared.",
        "MODCODES started as an open concept. The community shapes the product.",
        "CodeShortsBot — autonomous content pipeline. Fully documented. Fully open.",
        "Contributing to the ecosystem, not just consuming from it.",
      ],
      tags: ["Open Source", "GitHub", "Community", "Transparency"],
      links: [
        {
          label: "View GitHub",
          url: "https://github.com/aryan-sonsurkar",
          icon: "external",
        },
      ],
    },
  },
  {
    id: "developer-apartment",
    name: "Developer Apartment",
    subtitle: "Personal Space",
    position: [-9, 0, -5],
    scale: [2.2, 1.8, 2.2],
    color: "#d4c8b8",
    emissive: "#ff6b35",
    roofColor: "#5a4a3a",
    windowPattern: "grid",
    content: {
      title: "Developer Apartment",
      subtitle: "Where I Build",
      paragraphs: [
        "This is where it happens.",
        "Late nights. Early mornings. Coffee. Code.",
        "A mechanical keyboard that has seen more words than most novels. A monitor that never sleeps. A notebook full of ideas that started as scribbles and became products.",
        "The most honest room in the district.",
      ],
      tags: ["Personal", "Workspace", "Late Nights", "Coffee"],
      links: [],
    },
  },
];
