export type MonitorAssetType = "image" | "video" | "html" | "iframe" | "component";

export interface MonitorConfig {
  id: string;
  image: string;
  label: string;
  position: [number, number, number];
  rotation?: number;
  width: number;
  height: number;
  emissiveColor: string;
  assetType?: MonitorAssetType;
  info?: MonitorInfo;
}

// Progressive-disclosure content for the expanded viewer.
// Repo-truth only: neutral labels ("Demo on request") instead of invented data.
export interface MonitorInfo {
  title: string;
  summary: string;
  stack?: string;
  features?: string[];
  link?: string;
  linkLabel?: string;
}

export interface BuildingMonitors {
  room: { floorColor: string; ambientColor: string; ambientIntensity: number };
  ceilingLights: { color: string; x: number; z: number }[];
  monitors: MonitorConfig[];
  desks?: {
    position: [number, number, number];
    size: [number, number, number];
  }[];
  walls?: {
    position: [number, number, number];
    size: [number, number, number];
  }[];
  serverRacks?: [number, number, number][];
}

export const monitorConfig: Record<string, BuildingMonitors> = {
  "modcodes-hq": {
    room: { floorColor: "#12101a", ambientColor: "#b4c6e7", ambientIntensity: 0.5 },
    ceilingLights: [
      { color: "#ffd700", x: -3, z: -1 },
      { color: "#ffd700", x: 3, z: -1 },
      { color: "#3b82f6", x: 0, z: 1 },
    ],
    desks: [
      { position: [-2, 0, -1.2], size: [1.8, 0.07, 0.8] },
      { position: [0, 0, 0], size: [2.2, 0.07, 0.9] },
      { position: [2.5, 0, -1], size: [1.6, 0.07, 0.8] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    serverRacks: [[-4.2, 1.3, -1.8]],
    monitors: [
      {
        id: "modcodes-overview",
        image: "/monitors/hq/modcodes-overview.svg",
        label: "MODCODES OVERVIEW",
        position: [0, 0.8, -0.3],
        width: 1.3,
        height: 0.75,
        emissiveColor: "#7c9fc4",
        info: {
          title: "Modcodes",
          summary: "AI-powered student platform. Solves missed assignments, deadline chaos and disorganized planning.",
          stack: "Python · FastAPI · Ollama · SQLite",
          features: ["AI study assistance", "Assignment + deadline workflow", "Local-first, private by design"],
          link: "https://github.com/aryan-sonsurkar/mod-codes-ide",
          linkLabel: "Source",
        },
      },
      {
        id: "modcodes-features",
        image: "/monitors/hq/modcodes-features.svg",
        label: "MODCODES FEATURES",
        position: [-2, 0.8, -1.45],
        width: 1.1,
        height: 0.65,
        emissiveColor: "#22c55e",
        info: {
          title: "Modcodes features",
          summary: "Student workflows with local AI assistance, voice input and a calm workspace.",
          stack: "Python · FastAPI · Ollama · SQLite",
          features: ["AI assistance", "Student workflow", "Speech recognition + text-to-speech"],
          link: "https://github.com/aryan-sonsurkar/mod-codes-ide",
          linkLabel: "Source",
        },
      },
      {
        id: "modcodes-status",
        image: "/monitors/hq/modcodes-status.svg",
        label: "MODCODES STATUS",
        position: [2.5, 0.8, -1.25],
        width: 1.0,
        height: 0.6,
        emissiveColor: "#f59e0b",
        info: {
          title: "Modcodes status",
          summary: "Currently in Beta. A working product that students actually use — not a concept.",
          stack: "Python · FastAPI · Ollama · SQLite",
          link: "https://github.com/aryan-sonsurkar/mod-codes-ide",
          linkLabel: "Source",
        },
      },
      {
        id: "modcodes-arch",
        image: "/monitors/hq/modcodes-arch.svg",
        label: "MODCODES ARCHITECTURE",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.6,
        emissiveColor: "#3b82f6",
        info: {
          title: "Modcodes architecture",
          summary: "Student interface backed by FastAPI, with Ollama local LLMs and SQLite persistence.",
          stack: "Python · FastAPI · Ollama · SQLite",
          features: ["No cloud required", "Runs beside you"],
        },
      },
    ],
  },

  "achievement-tower": {
    room: { floorColor: "#0e0a18", ambientColor: "#ffe4b5", ambientIntensity: 0.5 },
    ceilingLights: [
      { color: "#f59e0b", x: -2, z: -1 },
      { color: "#f59e0b", x: 2, z: -1 },
    ],
    desks: [
      { position: [0, 0, -1.5], size: [1.6, 0.07, 0.7] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    monitors: [
      {
        id: "achievements-log",
        image: "/monitors/achievements/internship-certificate.svg",
        label: "ACHIEVEMENT LOG",
        position: [0, 0.8, -1.7],
        width: 1.0,
        height: 0.6,
        emissiveColor: "#f59e0b",
      },
      {
        id: "milestones",
        image: "/monitors/achievements/github-stats.svg",
        label: "MILESTONES",
        position: [0.5, 0.8, -1.3],
        rotation: -0.15,
        width: 0.7,
        height: 0.5,
        emissiveColor: "#22c55e",
      },
      {
        id: "linkedin",
        image: "/monitors/achievements/linkedin-growth.svg",
        label: "LINKEDIN MILESTONES",
        position: [2, 2.4, -2.9],
        width: 1.8,
        height: 1.0,
        emissiveColor: "#0077b5",
      },
      {
        id: "github-milestones",
        image: "/monitors/achievements/github-stats.svg",
        label: "GITHUB STATS",
        position: [4.9, 2.2, -1.5],
        rotation: -Math.PI / 2,
        width: 1.0,
        height: 0.7,
        emissiveColor: "#3b82f6",
      },
      {
        id: "leetcode",
        image: "/monitors/achievements/leetcode.svg",
        label: "LEETCODE",
        position: [-4.9, 2.2, 1],
        rotation: Math.PI / 2,
        width: 1.0,
        height: 0.7,
        emissiveColor: "#f59e0b",
      },
      {
        id: "edp-committee",
        image: "/monitors/achievements/edp-committee.svg",
        label: "EDP COMMITTEE",
        position: [0, 0.8, -0.5],
        rotation: 0.15,
        width: 0.9,
        height: 0.6,
        emissiveColor: "#ffd700",
      },
    ],
  },

  "developer-museum": {
    room: { floorColor: "#0d1210", ambientColor: "#ffe0b2", ambientIntensity: 0.5 },
    ceilingLights: [
      { color: "#ff6b35", x: -2, z: -1 },
      { color: "#22c55e", x: 2, z: -1 },
    ],
    desks: [
      { position: [-2, 0, -1], size: [1.6, 0.07, 0.7] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    monitors: [
      {
        id: "journey",
        image: "/monitors/museum/timeline.svg",
        label: "JOURNEY TIMELINE",
        position: [-2, 0.8, -1.2],
        width: 1.0,
        height: 0.6,
        emissiveColor: "#ff6b35",
      },
      {
        id: "first-laptop",
        image: "/monitors/museum/first-laptop.svg",
        label: "FIRST LAPTOP",
        position: [2.5, 1.1, -0.8],
        width: 0.5,
        height: 0.35,
        emissiveColor: "#22c55e",
      },
      {
        id: "full-journey",
        image: "/monitors/museum/timeline.svg",
        label: "THE JOURNEY",
        position: [0, 2.2, -2.9],
        width: 3.5,
        height: 1.8,
        emissiveColor: "#ff6b35",
      },
      {
        id: "pf-stack",
        image: "/monitors/museum/pf-stack.svg",
        label: "THIS WORLD · STACK",
        position: [-4.9, 2.2, -1],
        rotation: Math.PI / 2,
        width: 1.2,
        height: 0.8,
        emissiveColor: "#8fb8dd",
        info: {
          title: "How this world works · Stack",
          summary: "One codebase renders the landing page and the entire 3D district.",
          stack: "Next.js · React · TypeScript · Three.js · React Three Fiber · Zustand · Framer Motion · Web Audio",
        },
      },
      {
        id: "pf-world",
        image: "/monitors/museum/pf-world.svg",
        label: "THIS WORLD · DISTRICT",
        position: [4.9, 2.2, -1],
        rotation: -Math.PI / 2,
        width: 1.2,
        height: 0.8,
        emissiveColor: "#8fb8dd",
        info: {
          title: "How this world works · District",
          summary: "16-building data-driven district. Every room has a purpose, every monitor tells a story.",
          features: ["Interactive interiors", "Tap-to-inspect monitors", "Teleport + minimap navigation"],
        },
      },
      {
        id: "pf-controls",
        image: "/monitors/museum/pf-controls.svg",
        label: "THIS WORLD · CONTROLS",
        position: [-4.9, 1.1, 0.8],
        rotation: Math.PI / 2,
        width: 1.0,
        height: 0.6,
        emissiveColor: "#38bdf8",
        info: {
          title: "How this world works · Controls",
          summary: "First-person movement on desktop, joystick + tap on mobile. Teleport anywhere, ESC always exits.",
          features: ["WASD / joystick to move", "Click / tap monitors to inspect", "Teleport panel + minimap"],
        },
      },
      {
        id: "pf-performance",
        image: "/monitors/museum/pf-performance.svg",
        label: "THIS WORLD · PERFORMANCE",
        position: [4.9, 1.1, 0.8],
        rotation: -Math.PI / 2,
        width: 1.0,
        height: 0.6,
        emissiveColor: "#22c55e",
        info: {
          title: "How this world works · Performance",
          summary: "Quality tiers keep the district smooth on phones and desktops alike.",
          features: ["Auto / Performance / High tiers", "Capped pixel ratio", "Reduced effects on mobile"],
        },
      },
    ],
  },

  "project-factory": {
    room: { floorColor: "#0f1218", ambientColor: "#b4c6e7", ambientIntensity: 0.45 },
    ceilingLights: [
      { color: "#ef4444", x: -2, z: -1 },
      { color: "#3b82f6", x: 2, z: -1 },
    ],
    desks: [
      { position: [-2, 0, -1], size: [1.6, 0.07, 0.7] },
      { position: [2, 0, -1], size: [1.6, 0.07, 0.7] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    serverRacks: [[-4.2, 1.3, -1.8], [4.2, 1.3, -1.8]],
    monitors: [
      {
        id: "vishwanath",
        image: "/monitors/projects/vishwanath.svg",
        label: "VISHWANATH INSURANCE",
        position: [-4.9, 2.2, 0.3],
        rotation: Math.PI / 2,
        width: 1.2,
        height: 0.75,
        emissiveColor: "#22c55e",
        info: {
          title: "Vishwanath Insurance",
          summary: "Production client website with consultation workflow. Delivered and deployed.",
          stack: "Google Sheets integration · Responsive · Consultation workflow",
          features: ["Consultation booking flow", "Responsive, mobile-first", "Deployed on Vercel"],
          link: "https://vishwanath-malusare.vercel.app",
          linkLabel: "Live site",
        },
      },
      {
        id: "codeshorts",
        image: "/monitors/projects/codeshortsbot.svg",
        label: "CODESHORTS BOT v2",
        position: [4.9, 2.2, 0.3],
        rotation: -Math.PI / 2,
        width: 1.2,
        height: 0.75,
        emissiveColor: "#3b82f6",
        info: {
          title: "CodeShortsBot v2",
          summary: "Autonomous pipeline that turns code topics into short-form video. Zero human involvement.",
          stack: "Python · AI APIs · Automation",
          features: ["Topic research", "Script generation", "Video asset creation", "Multi-platform publishing"],
        },
      },
      {
        id: "fixly-overview",
        image: "/monitors/fixly/overview.svg",
        label: "FIXLY OVERVIEW",
        position: [-2, 0.8, -1.2],
        width: 1.05,
        height: 0.6,
        emissiveColor: "#22c55e",
        info: {
          title: "Fixly",
          summary: "AI-powered student workspace. Assignments, assistance, focus and notes in one calm place.",
          stack: "Next.js · React · AI/LLM workflows",
          features: ["Assignment tracking", "AI assistance", "Focus sessions + progress"],
          link: "https://fixly-student-assistant.vercel.app/",
          linkLabel: "Live site",
        },
      },
      {
        id: "fixly-assignments",
        image: "/monitors/fixly/assignments.svg",
        label: "FIXLY ASSIGNMENTS",
        position: [-1.3, 0.72, -0.95],
        rotation: -0.18,
        width: 0.7,
        height: 0.42,
        emissiveColor: "#f59e0b",
        info: {
          title: "Fixly assignments",
          summary: "Track every assignment by subject with clear status. Nothing slips through.",
          features: ["Subject-wise tracking", "Status at a glance", "Plan → submit flow"],
          link: "https://fixly-student-assistant.vercel.app/",
          linkLabel: "Live site",
        },
      },
      {
        id: "fixly-assistant",
        image: "/monitors/fixly/assistant.svg",
        label: "FIXLY AI ASSISTANT",
        position: [-4.9, 1.15, -1.6],
        rotation: Math.PI / 2,
        width: 1.0,
        height: 0.6,
        emissiveColor: "#38bdf8",
        info: {
          title: "Fixly AI assistant",
          summary: "Context-aware study help that plans sessions and answers from your material.",
          features: ["Study planning", "Concept explanations", "Focus timer handoff"],
          link: "https://fixly-student-assistant.vercel.app/",
          linkLabel: "Live site",
        },
      },
      {
        id: "fixly-tools",
        image: "/monitors/fixly/tools.svg",
        label: "FIXLY STUDY TOOLS",
        position: [-1.7, 2.3, -2.9],
        width: 1.4,
        height: 0.8,
        emissiveColor: "#22c55e",
        info: {
          title: "Fixly study tools",
          summary: "Focus sessions, quick notes, PDF analysis and screenshot OCR around your workflow.",
          features: ["Focus sessions", "Notes", "PDF analysis + screenshot OCR"],
          link: "https://fixly-student-assistant.vercel.app/",
          linkLabel: "Live site",
        },
      },
      {
        id: "kokanam-marketplace",
        image: "/monitors/kokanam/marketplace.svg",
        label: "KOKANAM MARKETPLACE",
        position: [2, 0.8, -1.2],
        width: 1.05,
        height: 0.6,
        emissiveColor: "#d9a441",
        info: {
          title: "Kokanam",
          summary: "Regional e-commerce marketplace. Products from brands across the Konkan region.",
          stack: "Marketplace · Built at Kaevron internship",
          features: ["Product discovery", "Brand catalog", "Customer accounts"],
          link: "https://www.kokanam.in/",
          linkLabel: "Live site",
        },
      },
      {
        id: "kokanam-products",
        image: "/monitors/kokanam/products.svg",
        label: "KOKANAM PRODUCT PAGE",
        position: [2.7, 0.72, -0.95],
        rotation: 0.18,
        width: 0.7,
        height: 0.42,
        emissiveColor: "#f59e0b",
        info: {
          title: "Kokanam product pages",
          summary: "Every product tells its origin story — maker, region and craft on one page.",
          features: ["Origin + maker story", "Add to cart", "Brand pages"],
          link: "https://www.kokanam.in/",
          linkLabel: "Live site",
        },
      },
      {
        id: "kokanam-customer",
        image: "/monitors/kokanam/customer.svg",
        label: "KOKANAM CUSTOMER FLOW",
        position: [4.9, 1.15, -1.6],
        rotation: -Math.PI / 2,
        width: 1.0,
        height: 0.6,
        emissiveColor: "#38bdf8",
        info: {
          title: "Kokanam customer flow",
          summary: "Browse to cart to account. Orders and history in one customer account.",
          features: ["Cart", "Customer accounts", "Order history"],
          link: "https://www.kokanam.in/",
          linkLabel: "Live site",
        },
      },
      {
        id: "kokanam-seller",
        image: "/monitors/kokanam/seller.svg",
        label: "KOKANAM SELLER ONBOARDING",
        position: [1.7, 2.3, -2.9],
        width: 1.4,
        height: 0.8,
        emissiveColor: "#d9a441",
        info: {
          title: "Kokanam seller onboarding",
          summary: "Konkan brands go from application to selling in four guided steps.",
          features: ["Guided application", "Verification", "Catalog + dashboard"],
          link: "https://www.kokanam.in/",
          linkLabel: "Live site",
        },
      },
    ],
  },

  "innovation-lab": {
    room: { floorColor: "#050d18", ambientColor: "#bfdbfe", ambientIntensity: 0.45 },
    ceilingLights: [
      { color: "#38bdf8", x: -2, z: -1 },
      { color: "#7c3aed", x: 2, z: -1 },
    ],
    desks: [
      { position: [-2, 0, -1], size: [1.6, 0.07, 0.7] },
      { position: [2, 0, -1], size: [1.6, 0.07, 0.7] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    serverRacks: [[-4.2, 1.3, -1.8], [4.2, 1.3, -1.8]],
    monitors: [
      {
        id: "ai-lab",
        image: "/monitors/innovation/ai-lab.svg",
        label: "AI/ML EXPERIMENTS",
        position: [-2, 0.8, -1.2],
        width: 1.0,
        height: 0.6,
        emissiveColor: "#38bdf8",
      },
      {
        id: "compiler",
        image: "/monitors/innovation/compiler.svg",
        label: "CUSTOM LANG / IDE",
        position: [2, 0.8, -1.2],
        width: 1.0,
        height: 0.6,
        emissiveColor: "#7c3aed",
      },
      {
        id: "research",
        image: "/monitors/innovation/roadmap.svg",
        label: "RESEARCH AGENDA",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.5,
        emissiveColor: "#38bdf8",
      },
    ],
  },

  "open-source-center": {
    room: { floorColor: "#051208", ambientColor: "#bbf7d0", ambientIntensity: 0.45 },
    ceilingLights: [
      { color: "#22c55e", x: -2, z: -1 },
      { color: "#22c55e", x: 2, z: -1 },
    ],
    desks: [
      { position: [0, 0, -1], size: [1.6, 0.07, 0.7] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    serverRacks: [[-3.8, 1.3, -1.8], [3.8, 1.3, -1.8]],
    monitors: [
      {
        id: "contributions",
        image: "/monitors/opensource/repositories.svg",
        label: "OPEN SOURCE BOARD",
        position: [0, 0.8, -1.2],
        width: 1.0,
        height: 0.6,
        emissiveColor: "#22c55e",
      },
      {
        id: "repos",
        image: "/monitors/opensource/contribution-graph.svg",
        label: "REPOSITORIES",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.5,
        emissiveColor: "#22c55e",
      },
    ],
  },

  "developer-apartment": {
    room: { floorColor: "#181218", ambientColor: "#ffe4b5", ambientIntensity: 0.5 },
    ceilingLights: [
      { color: "#ff8c42", x: -2, z: -1 },
      { color: "#3b82f6", x: 2, z: 1 },
      { color: "#ffd166", x: 0, z: -2 },
      { color: "#ff8c42", x: -3, z: 1 },
    ],
    desks: [
      { position: [-1.5, 0, -0.8], size: [2.0, 0.06, 0.9] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    monitors: [
      {
        id: "vscode",
        image: "/monitors/apartment/vscode.svg",
        label: "VS CODE EDITOR",
        position: [-1.8, 0.8, -1.05],
        width: 1.1,
        height: 0.65,
        emissiveColor: "#007acc",
      },
      {
        id: "spotify",
        image: "/monitors/apartment/spotify.svg",
        label: "NOW PLAYING",
        position: [-1.0, 0.8, -0.65],
        rotation: -0.2,
        width: 0.6,
        height: 0.45,
        emissiveColor: "#1db954",
      },
      {
        id: "whiteboard",
        image: "/monitors/apartment/ideas-board.svg",
        label: "IDEAS & NOTES",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.6,
        emissiveColor: "#f5f5f5",
      },
      {
        id: "github-graph",
        image: "/monitors/apartment/vscode.svg",
        label: "CONTRIBUTION GRAPH",
        position: [-4.9, 2.2, -1],
        rotation: Math.PI / 2,
        width: 1.2,
        height: 0.8,
        emissiveColor: "#22c55e",
      },
    ],
  },

  "football-arena": {
    room: { floorColor: "#0a2a0a", ambientColor: "#88ff88", ambientIntensity: 0.5 },
    ceilingLights: [
      { color: "#00ff88", x: -2, z: -1 },
      { color: "#00ff88", x: 2, z: -1 },
    ],
    desks: [
      { position: [-2, 0, -1], size: [1.2, 0.06, 0.6] },
      { position: [2, 0, -1], size: [1.2, 0.06, 0.6] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    monitors: [
      {
        id: "ronaldo-jersey",
        image: "/monitors/football/ronaldo-jersey.svg",
        label: "CR7 JERSEY",
        position: [-2, 1.0, -1.2],
        width: 1.0,
        height: 0.8,
        emissiveColor: "#ffd700",
      },
      {
        id: "trophy-collection",
        image: "/monitors/football/trophy-collection.svg",
        label: "TROPHY COLLECTION",
        position: [2, 1.0, -1.2],
        width: 1.0,
        height: 0.8,
        emissiveColor: "#ffd700",
      },
      {
        id: "football-moments",
        image: "/monitors/football/football-moments.svg",
        label: "FOOTBALL MOMENTS",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.5,
        emissiveColor: "#00ff88",
      },
      {
        id: "why-football",
        image: "/monitors/football/why-football.svg",
        label: "WHY FOOTBALL?",
        position: [-4.9, 2.2, -1],
        rotation: Math.PI / 2,
        width: 1.0,
        height: 0.8,
        emissiveColor: "#00ff88",
      },
    ],
  },

  "ironman-destiny-lab": {
    room: { floorColor: "#0d0808", ambientColor: "#ff8844", ambientIntensity: 0.5 },
    ceilingLights: [
      { color: "#ff6600", x: -2, z: -1 },
      { color: "#ff4400", x: 2, z: -1 },
    ],
    desks: [
      { position: [-2, 0, -1], size: [1.8, 0.07, 0.8] },
      { position: [2, 0, -1], size: [1.8, 0.07, 0.8] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    serverRacks: [[-4.2, 1.3, -1.8]],
    monitors: [
      {
        id: "arc-reactor",
        image: "/monitors/ironman/arc-reactor.svg",
        label: "ARC REACTOR BLUEPRINT",
        position: [-2, 0.8, -1.2],
        width: 1.0,
        height: 0.6,
        emissiveColor: "#00aaff",
      },
      {
        id: "ironman-glove",
        image: "/monitors/ironman/ironman-glove.svg",
        label: "IRON MAN GLOVE",
        position: [2, 0.8, -1.2],
        width: 1.0,
        height: 0.6,
        emissiveColor: "#ff4400",
      },
      {
        id: "workshop-schematics",
        image: "/monitors/ironman/workshop-schematics.svg",
        label: "WORKSHOP SCHEMATICS",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.5,
        emissiveColor: "#ff6600",
      },
      {
        id: "prototype-gallery",
        image: "/monitors/ironman/prototype-gallery.svg",
        label: "PROTOTYPE GALLERY",
        position: [-4.9, 2.2, -1],
        rotation: Math.PI / 2,
        width: 1.0,
        height: 0.8,
        emissiveColor: "#ff8800",
      },
    ],
  },

  "future-observatory": {
    room: { floorColor: "#050a14", ambientColor: "#88ccff", ambientIntensity: 0.5 },
    ceilingLights: [
      { color: "#00aaff", x: -2, z: -1 },
      { color: "#0066ff", x: 2, z: -1 },
    ],
    desks: [
      { position: [0, 0, -1], size: [2.0, 0.07, 0.8] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    monitors: [
      {
        id: "vision-board",
        image: "/monitors/observatory/vision-board.svg",
        label: "VISION BOARD",
        position: [0, 0.8, -1.2],
        width: 1.2,
        height: 0.7,
        emissiveColor: "#00aaff",
      },
      {
        id: "roadmap-2026",
        image: "/monitors/observatory/roadmap-2026.svg",
        label: "2026 ROADMAP",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.5,
        emissiveColor: "#0066ff",
      },
      {
        id: "skills-evolution",
        image: "/monitors/observatory/skills-evolution.svg",
        label: "SKILLS EVOLUTION",
        position: [-4.9, 2.2, -1],
        rotation: Math.PI / 2,
        width: 1.0,
        height: 0.8,
        emissiveColor: "#00ccff",
      },
      {
        id: "career-goals",
        image: "/monitors/observatory/career-goals.svg",
        label: "CAREER GOALS",
        position: [4.9, 2.2, -1],
        rotation: -Math.PI / 2,
        width: 1.0,
        height: 0.8,
        emissiveColor: "#0088ff",
      },
    ],
  },
  "contact-kiosk": {
    room: { floorColor: "#1a0a2a", ambientColor: "#a855f7", ambientIntensity: 0.5 },
    ceilingLights: [
      { color: "#a855f7", x: 0, z: 0 },
    ],
    monitors: [
      {
        id: "contact-links",
        image: "/monitors/contact/contact-links.svg",
        label: "CONTACT LINKS",
        position: [0, 2.2, -2.9],
        width: 2.0,
        height: 1.2,
        emissiveColor: "#a855f7",
      },
    ],
  },

  "algorithm-dojo": {
    room: { floorColor: "#0a0e18", ambientColor: "#bfdbfe", ambientIntensity: 0.5 },
    ceilingLights: [
      { color: "#38bdf8", x: -2, z: -1 },
      { color: "#f59e0b", x: 2, z: -1 },
    ],
    desks: [
      { position: [0, 0, -1], size: [2.0, 0.07, 0.8] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    monitors: [
      {
        id: "dojo-rating",
        image: "/monitors/dojo/rating-chart.svg",
        label: "RATING CHART",
        position: [0, 0.8, -1.7],
        width: 1.2,
        height: 0.7,
        emissiveColor: "#38bdf8",
      },
      {
        id: "dojo-100-days",
        image: "/monitors/dojo/streak.svg",
        label: "100 DAY STREAK",
        position: [-2, 0.8, -1.2],
        width: 0.9,
        height: 0.6,
        emissiveColor: "#f59e0b",
      },
      {
        id: "dojo-solved",
        image: "/monitors/dojo/solved.svg",
        label: "PROBLEMS SOLVED",
        position: [2, 0.8, -1.2],
        width: 0.9,
        height: 0.6,
        emissiveColor: "#22c55e",
      },
      {
        id: "dojo-wall",
        image: "/monitors/dojo/rating-chart.svg",
        label: "LEADERBOARD",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.5,
        emissiveColor: "#38bdf8",
      },
    ],
  },

  "hardware-foundry": {
    room: { floorColor: "#0a1208", ambientColor: "#bbf7d0", ambientIntensity: 0.45 },
    ceilingLights: [
      { color: "#22c55e", x: -2, z: -1 },
      { color: "#ef4444", x: 2, z: -1 },
    ],
    desks: [
      { position: [-2, 0, -1], size: [1.6, 0.07, 0.7] },
      { position: [2, 0, -1], size: [1.6, 0.07, 0.7] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    serverRacks: [[-4.2, 1.3, -1.8]],
    monitors: [
      {
        id: "tinkerer",
        image: "/monitors/foundry/esp32.svg",
        label: "ESP32 WORKBENCH",
        position: [0, 0.8, -1.7],
        width: 1.0,
        height: 0.6,
        emissiveColor: "#22c55e",
      },
      {
        id: "foundry-traffic",
        image: "/monitors/foundry/traffic-light.svg",
        label: "TRAFFIC LIGHT PROTOTYPE",
        position: [-2, 0.8, -1.2],
        width: 0.9,
        height: 0.6,
        emissiveColor: "#ef4444",
      },
      {
        id: "foundry-oled",
        image: "/monitors/foundry/oled.svg",
        label: "OLED DISPLAY LAB",
        position: [2, 0.8, -1.2],
        width: 0.9,
        height: 0.6,
        emissiveColor: "#38bdf8",
      },
      {
        id: "foundry-wall",
        image: "/monitors/foundry/esp32.svg",
        label: "FOUNDRY BLUEPRINTS",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.5,
        emissiveColor: "#22c55e",
      },
    ],
  },

  "the-vault": {
    room: { floorColor: "#120c06", ambientColor: "#fde68a", ambientIntensity: 0.4 },
    ceilingLights: [
      { color: "#ffd700", x: -2, z: -1 },
      { color: "#8b5cf6", x: 2, z: -1 },
    ],
    desks: [
      { position: [0, 0, -1], size: [1.8, 0.07, 0.8] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    serverRacks: [[-4.2, 1.3, -1.8], [4.2, 1.3, -1.8]],
    monitors: [
      {
        id: "seema-overview",
        image: "/monitors/seema/overview.svg",
        label: "SEEMA NETRA OVERVIEW",
        position: [0, 0.8, -1.7],
        width: 1.1,
        height: 0.65,
        emissiveColor: "#38bdf8",
        info: {
          title: "Seema Netra",
          summary: "AI-powered video surveillance prototype. Detects, tracks and logs events — with human verification.",
          stack: "YOLOv8 · ByteTrack · OpenCV · FastAPI · React/Vite · SQLite",
          features: ["Object detection + tracking", "Boundary intrusion detection", "Loitering detection", "Evidence snapshots + incident logging"],
          linkLabel: "Demo on request",
        },
      },
      {
        id: "seema-tracking",
        image: "/monitors/seema/tracking.svg",
        label: "OBJECT TRACKING",
        position: [-4.9, 2.2, -0.5],
        rotation: Math.PI / 2,
        width: 1.2,
        height: 0.75,
        emissiveColor: "#22c55e",
        info: {
          title: "Seema Netra tracking",
          summary: "YOLOv8 detections linked into persistent tracks with ByteTrack, processed through OpenCV.",
          stack: "YOLOv8 · ByteTrack · OpenCV",
          features: ["Per-frame detection", "Persistent track IDs", "Monitored boundary zones"],
          linkLabel: "Demo on request",
        },
      },
      {
        id: "seema-incidents",
        image: "/monitors/seema/incidents.svg",
        label: "INCIDENT LOG",
        position: [4.9, 2.2, -0.5],
        rotation: -Math.PI / 2,
        width: 1.2,
        height: 0.75,
        emissiveColor: "#f59e0b",
        info: {
          title: "Seema Netra incidents",
          summary: "Intrusions and loitering events are logged with evidence snapshots for operator review.",
          stack: "FastAPI · SQLite · React/Vite",
          features: ["Boundary intrusion log", "Loitering detection", "Evidence snapshots", "Human verification step"],
          linkLabel: "Demo on request",
        },
      },
      {
        id: "seema-arch",
        image: "/monitors/seema/arch.svg",
        label: "SYSTEM ARCHITECTURE",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.5,
        emissiveColor: "#38bdf8",
        info: {
          title: "Seema Netra architecture",
          summary: "Browser UI served over a FastAPI backend driving the vision pipeline and SQLite store.",
          stack: "React/Vite · FastAPI · YOLOv8 · ByteTrack · OpenCV · SQLite",
          linkLabel: "Demo on request",
        },
      },
      {
        id: "curator",
        image: "/monitors/vault/plaque.svg",
        label: "THE PLAQUE",
        position: [-4.9, 1.7, -1],
        rotation: Math.PI / 2,
        width: 0.7,
        height: 0.5,
        emissiveColor: "#8b5cf6",
      },
    ],
  },

  "hackathon-war-room": {
    room: { floorColor: "#160a0a", ambientColor: "#fecaca", ambientIntensity: 0.4 },
    ceilingLights: [
      { color: "#ef4444", x: -2, z: -1 },
      { color: "#f59e0b", x: 2, z: -1 },
    ],
    desks: [
      { position: [-2, 0, -1], size: [1.6, 0.07, 0.7] },
      { position: [2, 0, -1], size: [1.6, 0.07, 0.7] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    monitors: [
      {
        id: "survivor",
        image: "/monitors/warroom/sih-board.svg",
        label: "SIH-2025 MISSION",
        position: [0, 0.8, -1.7],
        width: 1.1,
        height: 0.65,
        emissiveColor: "#ef4444",
      },
      {
        id: "warroom-whiteboard",
        image: "/monitors/warroom/whiteboard.svg",
        label: "WAR WHITEBOARD",
        position: [-2, 0.8, -1.2],
        width: 0.9,
        height: 0.6,
        emissiveColor: "#f59e0b",
      },
      {
        id: "warroom-timeline",
        image: "/monitors/warroom/timeline.svg",
        label: "48H TIMELINE",
        position: [2, 0.8, -1.2],
        width: 0.9,
        height: 0.6,
        emissiveColor: "#38bdf8",
      },
      {
        id: "warroom-wall",
        image: "/monitors/warroom/sih-board.svg",
        label: "MISSION CONTROL",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.5,
        emissiveColor: "#ef4444",
      },
    ],
  },

  "the-roastery": {
    room: { floorColor: "#14100c", ambientColor: "#fce7f3", ambientIntensity: 0.5 },
    ceilingLights: [
      { color: "#c084fc", x: -2, z: -1 },
      { color: "#c084fc", x: 2, z: -1 },
      { color: "#f59e0b", x: 0, z: -2 },
    ],
    desks: [
      { position: [0, 0, -1], size: [2.2, 0.07, 0.9] },
    ],
    walls: [
      { position: [0, 2.3, -3], size: [10, 4.8, 0.15] },
      { position: [0, 2.3, 3], size: [10, 4.8, 0.15] },
      { position: [-5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [5, 2.3, 0], size: [0.15, 4.8, 6.2] },
      { position: [0, 4.75, 0], size: [10.2, 0.15, 6.2] },
      { position: [0, 0, 0], size: [10, 0.12, 6] },
    ],
    monitors: [
      {
        id: "coffee-break",
        image: "/monitors/roastery/now-brewing.svg",
        label: "NOW BREWING",
        position: [0, 0.8, -1.5],
        width: 1.0,
        height: 0.6,
        emissiveColor: "#c084fc",
      },
      {
        id: "roastery-beans",
        image: "/monitors/roastery/bean-counter.svg",
        label: "BEANS COUNTED",
        position: [-2, 0.8, -1.2],
        width: 0.8,
        height: 0.5,
        emissiveColor: "#a0522d",
      },
      {
        id: "roastery-playlist",
        image: "/monitors/roastery/playlist.svg",
        label: "CAFE PLAYLIST",
        position: [0, 2.4, -2.9],
        width: 3.0,
        height: 1.5,
        emissiveColor: "#c084fc",
      },
    ],
  },
};
